version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: apps/next-weight-tracker/Dockerfile
    container_name: frontend
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_API_URL=/api

  backend:
    build:
      context: .
      dockerfile: apps/nestjs-weight-tracker/Dockerfile
    container_name: backend
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgresql://appuser:strongpass@db:5432/weight_tracker_db
      - CLIENT_URL=http://localhost
      - JWT_ACCESS_SECRET=access-secret-key
      - JWT_REFRESH_SECRET=refresh-secret-key

  db:
    image: postgres:15
    container_name: db
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: strongpass
      POSTGRES_DB: weight_tracker_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge