name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy on VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@194.87.254.169 << 'EOF'
            cd ~/weight-tracker-apps
            git pull origin main
            docker compose down
            docker compose build --no-cache
            docker compose up -d
          EOF